### ISSUE TITLE
Fix slot 16 on shops

### ISSUE THREAD

**Issue by CelestialCrafter** [WSMAFarms/Issues#1]
Slot 16 in every page of /shop gui there is nothing. And the item thats supposed to be in slot 16 is in slot 1 instead

![Screen_Shot_2020-08-28_at_12 11 14_PM](https://user-images.githubusercontent.com/44733683/91594901-a38f4900-e930-11ea-8ad3-70d84e986cbd.png)

**Comment by 1Winterxq** [comment]
Fixed!
