### ISSUE TITLE
Add sell prices

### ISSUE THREAD

**Issue by CelestialCrafter** [WSMAFarms/Issues#4]
The prices for /sell need to be added

There should be a /worth command that lists all sell prices and all sellable items

**Comment by CelestialCrafter** [comment]
Wheat - 7.5$ for 1 wheat

Carrot/Potato: 12$ for 1 carrot/potato

Beetroot: 15$ for 1 beetroot

Pumpkin: 20$ for 1 pumpkin

Melon: 25$ for 1 melon slice

Sugarcane: 50$ for 1 sugarcane

Cactus: 100$ for 1 cactus

**Comment by 1Winterxq** [comment]
/sell has now been added, and sell prices appear on shop.

**Comment by 1Winterxq** [comment]
Added/Fixed
